<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="articubot">
    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="forearm_radius" value="0.02" />
    <xacro:property name="forearm_length" value="0.1" />
    <xacro:property name="hand_radius" value="0.02" />
    <xacro:property name="hand_length" value="0.15" />
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                     iyy="1.0" iyz="0.0"
                     izz="1.0" />
        </inertial>
    </xacro:macro>
    <xacro:property name="PI" value="3.14159265359" />
    <xacro:property name="effort" value="30.0" />
    <xacro:property name="velocity" value="10.0" />
    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${(arm_base_height / 2.0)+0.02}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.5" l="${2*arm_base_length}" w="${2*arm_base_width}" h="${2*arm_base_height}" 
                           xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0" />
    </link>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length / 2.0}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*forearm_radius}" h="${2*forearm_length}"
                                xyz="0 0 ${forearm_length / 2.0}" rpy="0 0 0" />
    </link>

    <link name="hand_1_link">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
             <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*hand_radius}" h="${2*hand_length}"
                                xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
    </link>

    <link name="hand_2_link">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
             <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*hand_radius}" h="${2*hand_length}"
                                xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
    </link>

    <link name="hand_3_link">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
             <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*hand_radius}" h="${2*hand_length}"
                                xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
    </link>

    <link name="claw_support">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length/8}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 16.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
             <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*hand_radius}" h="${2*hand_length}"
                                xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
    </link>

    <link name="gripper_right">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
             <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*hand_radius}" h="${2*hand_length}"
                                xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
    </link>

    <link name="gripper_left">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
             <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*hand_radius}" h="${2*hand_length}"
                                xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
    </link>

    <!-- <joint name="mobile_base_arm_joint" type="fixed">
        <parent link="chassis" />
        <child link="arm_base_link" />
        <origin xyz="${8*chassis_length / 9.0} 0 ${chassis_height}" rpy="0 0 0" />
    </joint> -->

    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

    <joint name="forearm_hand_1_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_1_link" />
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

    <joint name="forearm_hand_2_joint" type="revolute">
        <parent link="hand_1_link" />
        <child link="hand_2_link" />
        <origin xyz="0 0 ${hand_length}" rpy="0 0 ${pi}" />
        <axis xyz="0 1 0" />
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

    <joint name="forearm_hand_3_joint" type="revolute">
        <parent link="hand_2_link" />
        <child link="hand_3_link" />
        <origin xyz="0 0 ${hand_length}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

    <joint name="forearm_claw_joint" type="revolute">
        <parent link="hand_3_link" />
        <child link="claw_support" />
        <origin xyz="0 0 ${hand_length}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

    <joint name ="joint_4" type="revolute">
        <parent link="claw_support"/>
        <child link = "gripper_right"/>
        <origin xyz="0 0.05 ${hand_length/8}"/>
        <axis xyz="1 0 0"/>
        <limit lower="-${PI / 2}" upper="0.0" 
               effort="100" velocity="100"/>
    </joint>
    <joint name ="joint_5" type="revolute">
        <parent link="claw_support"/>
        <child link = "gripper_left"/>
        <origin xyz="0 -.05 ${hand_length/8}"/>
        <axis xyz="1 0 0"/>
        <limit lower="0.0" upper="${PI / 2}" 
               effort="100" velocity="100"/>
        <mimic joint="joint_4" multiplier="-1"/>
    </joint>
</robot>