# Default initial positions for arduinobot's ros2_control fake system

initial_positions:
  # left_wheel_joint: 0
  # right_wheel_joint: 0
  arm_base_forearm_joint: 0
  forearm_hand_1_joint: 0.2
  forearm_hand_2_joint: 0.2
  forearm_hand_3_joint: 0.2
  forearm_claw_joint: 0
  joint_4: 0
